/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-license-content.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />

declare namespace UiElements {

  /**
   * License dialog content.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-license-content` | Mixin applied to this elment | `{}`
   * `--arc-license-section-title-color` | Color of section title | `--primary-color`
   */
  class ArcLicenseContent extends Polymer.Element {
  }
}

interface HTMLElementTagNameMap {
  "arc-license-content": UiElements.ArcLicenseContent;
}
