/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   arc-license-content.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare namespace UiElements {

  /**
   * License dialog content.
   *
   * ## Styling
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--arc-license-section-title-color` | Color of section title | `--primary-color`
   */
  class ArcLicenseContent extends PolymerElement {
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "arc-license-content": UiElements.ArcLicenseContent;
  }
}

export {};
